### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [dajare/margaret-oliphant_phoebe-junior#1]
# Typography

- [x] chapter-29: Typogrify changes a no-break space (`U+00A0`) in front of “etc.” into a normal space. I think you should accept that change, since there is nothing in the manual calling for that.

# Spelling

- [x] chapter-45: Looks like modernize-spelling changed `tho’` to `though` in a dialectical context. I would revert.
- [x] chapter-8: I don’t think *Jane Eyre* establishes any precendent for “Hindostanee.” Both books should be changed to say “Hindustani” as Ngrams would suggest.

# Semantics

- [x] chapter-13: I think “Congregational Magazine” should receive italics and title semantics.

# Colophon

- [x] Eugeniusz Wrzeszcz should be in `<b epub:type="z3998:personal-name">`.

**Comment by dajare** [comment]
I think that's all taken care of now, @weijia-cheng - there were a few "Doh!" items in there!

Re: "Hindostanee" - that was my inclination, too, but given the Jane Eyre "precedent", wasn't sure. It seems close enough to "sound-alike" for mod-spell to me.

Thanks once more for another sharp review! If you're happy, it's over to Alex.
